require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1
  Exclude:
    - vendor/**/*
    - log/**/*
    - tmp/**/*
    - storage/**/*
    - lib/tasks/**/*
    - bin/*

Style/Documentation:
  Enabled: False
