default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  url: 'postgres://cs:123@localhost:5433'

development:
  <<: *default
  database: counter_strike_development

test:
  <<: *default
  database: counter_strike_test

production:
  <<: *default
  database: counter_strike_production
